### ISSUE TITLE
Automatic beta updates and releases

### ISSUE THREAD

**Issue by AsCress** [fossasia/badge-magic-android#1222]
We're aiming for two things here:
1. Currently, whenever we push to the _flutter_app_ branch, the build gets pushed to the _beta_ tracks in both the _Play Store_ and the _App Store_. We may as well make new **GitHub** releases for each push (beta releases). The stable release would always be marked with the _Latest_ tag, and the beta releases would co-exist along with it.
2.  **F-Droid beta integration**:- As we do with the _Play Store_ and the _App Store_, we may also aim to push _beta_ releases to F-Droid. However, there's a problem here: F-Droid doesn't support **automatic** beta updates. 

Here's some more information on this:

## Pushing to beta on F-Droid
The section of the F-Droid _Build Metadata_ that handles builds and versioning looks something like this:
```
Builds:
  - versionName: 1.5.0
    versionCode: 7
    commit: v1.5.0
    subdir: app
    gradle:
      - yes
    prebuild: sed -i -e '/LOCAL_KEY/d' build.gradle

  - versionName: 1.6.0
    versionCode: 8
    commit: v1.6.0
    subdir: app
    gradle:
      - yes
    prebuild: sed -i -e '/LOCAL_KEY/d' build.gradle

  - versionName: 1.7.0
    versionCode: 9
    commit: v1.7.0
    subdir: android
    gradle:
      - yes
    prebuild:
      - sed -i -e '/LOCAL_KEY/d' build.gradle
      - echo -e '\n' 'org.gradle.jvmargs=-Xmx1g' >> ../gradle.properties

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.7.0
CurrentVersionCode: 9

```
That is, a list of all the uploaded builds till now (the _Builds_ section), along with a specification of the latest **stable** (or **suggested** in F-Droid language) build (the _CurrentVersion_ and _CurrentVersionCode_ fields). The way to push to beta on F-Droid is to just add new builds to the _Builds_ section without updating the _CurrentVersion_ and _CurrentVersionCode_ fields. In this way, F-Droid builds the app, and it gets listed on the F-Droid store, but it isn't marked as a **Suggested** release. Only the release with the versionCode and versionName matching with the _CurrentVersion_ and _CurrentVersionCode_ fields is marked as the ONE and ONLY **stable/suggested** release.

## Can we do this process automatically ?
Using F-Droid APIs? **No**, unfortunately. F-Droid runs an automatic check periodically on all repos, and updates them regularly based on the methods specified in _AutoUpdateMode_ and _UpdateCheckMode_ fields. Whenever it detects an update, it adds a new build to the _Builds_ sections and updates the _CurrentVersion_ and _CurrentVersionCode_ fields in the Build Metadata.
In this way, the latest release is always marked as the **Suggested** release: something which we don't want for our beta releases. There has been a lot of discussion before in the F-Droid community regarding this but there is unfortunately no solution to handle this process automatically.
Going through many repos on F-Droid which push both **beta** and **stable** releases to F-Droid, I found out that each of them updates their app manually through merge requests on GitLab, which seems to be the only way to handle this situation till now.

## My Proposal
Since F-Droid APIs don't provide us a method to do this, the only way to do this boils down to creating a merge request on GitLab for the same.
Can we do that automatically ? **YES** !! GitLab provides `glab`, a command line tool to interface with GitLab, which also provides methods to work with merge requests through command line. We can automatically create merge requests directly (`glab mr create` to be specific) from our pipelines for each new push to update the beta version on F-Droid.
Again, this is my proposal, there may be better ways to handle this.

@adityastic @Jhalakupadhyay Let me know how all this sounds to you.

### References
1. https://gitlab.com/fdroid/fdroidserver/-/issues/112 
2. https://gitlab.com/fdroid/fdroidserver/-/issues/161
3. https://forum.f-droid.org/t/provide-beta-versions-of-andotp/2583
4. https://f-droid.org/en/docs/Build_Metadata_Reference/
5. https://f-droid.org/en/docs/Update_Processing/
6. https://docs.gitlab.com/editor_extensions/gitlab_cli/
